version: '3'

services:
  thinkbox:
    image: 'thinkbox'
    ports:
      - 8000:8000
    volumes:
      - ./.env:/thinkbox/.env
    depends_on:
      database:
        condition: service_healthy
  database:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    env_file:
      - .env
    volumes:
      - type: volume
        source: thinkbox_database
        target: /var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
volumes:
  thinkbox_database: