version: '3'

services:
  thinkbox:
    image: 'thinkbox'
    ports:
      - 8080:8000
    volumes:
      - ./database.config:/thinkbox/database.config
    depends_on:
      database:
        condition: service_healthy
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: think 
      POSTGRES_PASSWORD: ehGzT3Pr # this password is not used in production
      POSTGRES_DB: thinkbox
    volumes:
          - ./db-data/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "thinkbox"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
 
 